BOOTMAGIC_ENABLE = no
VIA_ENABLE = no
OS_DETECTION_DEBUG_ENABLE = no
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no
TAP_DANCE_ENABLE = no

SPLIT_KEYBOARD = yes
RGB_MATRIX_ENABLE = yes
LEADER_ENABLE = yes
